name: eventos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_functions: ^5.1.4
  country_code_picker: ^3.1.0
  country_picker: ^2.0.26
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  intl_phone_number_input: ^0.7.4
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
